name: Build Weekly Release

on:
  workflow_dispatch:
  schedule:
    - cron: '10 0 * * 3'
  ## For testing only!
  # push:
  #   branches:
  #     - feat/unity-cloud-build

jobs:
  get-info:
    name: Get Info
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      latest_version: ${{ steps.get_version.outputs.latest_version }}
      full_version: ${{ steps.get_version.outputs.next_full_version }}
      tag_version: ${{ steps.get_version.outputs.next_tag_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        uses: ./.github/actions/version

  # Run a clean build (no cache)
  build:
    name: Build Unity Cloud
    needs: get-info
    uses: ./.github/workflows/build-unitycloud.yml
    with:
      profile: none
      cache: false
      version: ${{ needs.get-info.outputs.full_version }}
    secrets: inherit
